name: C Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang-format cppcheck check valgrind

      - name: Run clang-format (Check Style)
        run: |
          find . -type f -name "*.c" -o -name "*.h" | xargs clang-format -i
          git diff --exit-code --color || (echo "Code is not formatted. Run clang-format." && exit 1)

      - name: Run cppcheck (Static Analysis)
        run: cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem .

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests with valgrind (Memory Leak Check)
        run: |
          cd build
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 .run_tests
